# Config file for automatic testing at travis-ci.org

language: python
dist: focal
python:
  - "3.11"


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - make dist && pip install dist/*whl

# Command to run tests, e.g. python setup.py test
script:
    #- coverage run --source cansrmapp -m unittest discover
    - cd demo && sh build.sh && sh test-solve.sh

vm :
    size : large

#after_success: coveralls


